version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update -y
            apt-get install -y python3
      - run:
          name: Run tests
          command: |
            cd test
            ./test.sh
