name: Main

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, ubuntu-16.04]
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install shellcheck python3 python3-setuptools bc -y
    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update
        brew install python3
    - name: Python dependencys
      run: python3 -m pip install -r requirements.txt
    - name: Test on Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd test
        ./test.sh --verbose
    - name: Shellcheck on Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        echo "todo"; # shellcheck start_tem.sh
